/**
 * Erasable const-object enums. `erasableSyntaxOnly` is enabled in tsconfig.app.json,
 * which forbids TS `enum` declarations. This pattern keeps identical call-site
 * ergonomics (`TvType.Movie` as a value, `TvType` as a type) while emitting nothing
 * that requires type-directed transformation.
 */
export const TvType = {
  Movie: 'Movie',
  TvSeries: 'TvSeries',
  Anime: 'Anime',
  AnimeMovie: 'AnimeMovie',
  OVA: 'OVA',
  Documentary: 'Documentary',
  Live: 'Live',
  NSFW: 'NSFW',
  AsianDrama: 'AsianDrama',
  Torrent: 'Torrent',
} as const;
export type TvType = (typeof TvType)[keyof typeof TvType];

export const DubStatus = {
  Subbed: 'Subbed',
  Dubbed: 'Dubbed',
  Raw: 'Raw',
} as const;
export type DubStatus = (typeof DubStatus)[keyof typeof DubStatus];

export const WatchStatus = {
  Watching: 'Watching',
  Completed: 'Completed',
  OnHold: 'OnHold',
  PlanToWatch: 'PlanToWatch',
  Dropped: 'Dropped',
} as const;
export type WatchStatus = (typeof WatchStatus)[keyof typeof WatchStatus];

export const BUCKET_LABELS: Record<WatchStatus, string> = {
  Watching: 'Watching',
  Completed: 'Completed',
  OnHold: 'On hold',
  PlanToWatch: 'Plan to watch',
  Dropped: 'Dropped',
};

export interface SearchResponse {
  name: string;
  url: string;
  apiName: string;
  type?: TvType;
  posterUrl?: string;
  posterHeaders?: Record<string, string>;
  year?: number;
  quality?: string;
  id?: number;
}

/**
 * One autocomplete row under the search box.
 *
 * Distinct from {@link SearchResponse}: this describes a *title* the user might
 * mean, merged across every catalogue that knows about it, and carries the
 * extra context that makes a guess resolvable at a glance — the official
 * spelling, the year, and a line of plot. `sources` records which catalogues
 * agreed, which is the strongest available signal that a row is the real thing
 * rather than one catalogue's fuzzy near-miss.
 */
export interface SearchSuggestion {
  /** The catalogue's official title, which is what should be searched. */
  title: string;
  year?: number;
  type?: TvType;
  posterUrl?: string;
  plot?: string;
  genres: string[];
  /** Catalogue URL, so a suggestion can open the title directly. */
  url: string;
  imdbId?: string;
  /** Catalogues that independently returned this title. */
  sources: string[];
}

/** One past search, newest first. */
export interface SearchHistoryEntry {
  query: string;
  /** Epoch millis of the most recent time this query was run. */
  at: number;
  /** How many results it produced, so a fruitless query looks different. */
  resultCount?: number;
}

export interface Episode {
  name: string;
  url: string;
  episode?: number;
  season?: number;
  posterUrl?: string;
  rating?: number;
  description?: string;
  date?: string;
}

export interface LoadResponse {
  name: string;
  url: string;
  apiName: string;
  type: TvType;
  posterUrl?: string;
  year?: number;
  plot?: string;
  rating?: number;
  tags?: string[];
  duration?: string;
  episodes?: Episode[];
  actors?: string[];
  recommendations?: SearchResponse[];
  id?: number;
}

export interface ExtractorLink {
  source: string;
  name: string;
  url: string;
  referer: string;
  quality: number; // e.g. 1080, 720, 480, 360
  isM3u8?: boolean;
  isDash?: boolean;
  headers?: Record<string, string>;
  subtitles?: SubtitleFile[];
}

export interface SubtitleFile {
  url: string;
  lang: string;
  isAutoGenerated?: boolean;
}

export interface Score {
  value: number; // 0 to 10 scale
}
