export enum TvType {
  Movie = 'Movie',
  TvSeries = 'TvSeries',
  Anime = 'Anime',
  AnimeMovie = 'AnimeMovie',
  OVA = 'OVA',
  Documentary = 'Documentary',
  Live = 'Live',
  NSFW = 'NSFW',
  AsianDrama = 'AsianDrama',
  Torrent = 'Torrent',
}

export enum DubStatus {
  Subbed = 'Subbed',
  Dubbed = 'Dubbed',
  Raw = 'Raw',
}

export interface SearchResponse {
  name: string;
  url: string;
  apiName: string;
  type?: TvType;
  posterUrl?: string;
  posterHeaders?: Record<string, string>;
  year?: number;
  quality?: string;
  id?: number;
}

export interface Episode {
  name: string;
  url: string;
  episode?: number;
  season?: number;
  posterUrl?: string;
  rating?: number;
  description?: string;
  date?: string;
}

export interface LoadResponse {
  name: string;
  url: string;
  apiName: string;
  type: TvType;
  posterUrl?: string;
  year?: number;
  plot?: string;
  rating?: number;
  tags?: string[];
  duration?: string;
  episodes?: Episode[];
  actors?: string[];
  recommendations?: SearchResponse[];
  id?: number;
}

export interface ExtractorLink {
  source: string;
  name: string;
  url: string;
  referer: string;
  quality: number; // e.g. 1080, 720, 480, 360
  isM3u8?: boolean;
  isDash?: boolean;
  headers?: Record<string, string>;
  subtitles?: SubtitleFile[];
}

export interface SubtitleFile {
  url: string;
  lang: string;
  isAutoGenerated?: boolean;
}

export interface Score {
  value: number; // 0 to 10 scale
}
